/**/*:
  ros__parameters:
    broker:
      host: ak-win11
      port: 1883
    bridge:
      ros2mqtt:
        ros_topics:
          - /imu
          - /pointcloud
        /imu:
          mqtt_topic: mqtt/imu
          primitive: false
          ros_type: sensor_msgs/msg/Imu
          advanced:
            ros:
              queue_size: 10
              qos:
                durability: auto
                reliability: auto
        /pointcloud:
          mqtt_topic: mqtt/pointcloud
          primitive: false
          ros_type: sensor_msgs/msg/PointCloud2
          advanced:
            ros:
              queue_size: 10
              qos:
                durability: auto
                reliability: auto
      mqtt2ros:
        mqtt_topics:
          - mqtt/joy
        mqtt/joy:
          ros_topic: /joy
          primitive: false
          ros_type: sensor_msgs/msg/Joy
          advanced:
            ros:
              queue_size: 10
              qos:
                durability: transient_local
                reliability: reliable
