# Site settings
title: AKROS2
description: ROS 2 software stack for mecanum-wheeled mobile robots
author: Aditya Kamath

# Beautiful Jekyll theme
remote_theme: daattali/beautiful-jekyll@6.0.1

# Personalization - use header image as logo in top left
title-img: /akros2/assets/img/header_image.png
navbar-links: {}

# Social network links
social-network-links:
  website: https://kamathrobotics.com
  email: adityakamath@live.com
  github: adityakamath
  twitter: kamathsblog
  linkedin: adityakamath
  youtube: AdityaKamath2405
  rss: true

# URL configuration
url: "https://adityakamath.github.io"
baseurl: "/akros2"

# Markdown and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM

# Timezone
timezone: America/Vancouver

# Permalink structure
permalink: /:year-:month-:day-:title/

# Excerpt settings
excerpt_length: 50

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 5

# Post settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true
